// src/lib/ai.js

/**
 * AI Service for Website Content Generation
 * Uses Anthropic Claude API to generate website copy
 */

import Anthropic from '@anthropic-ai/sdk';

// Initialize the Anthropic client
// The API key is read from environment variables
const getAnthropicClient = () => {
  const apiKey = import.meta.env.VITE_ANTHROPIC_API_KEY;
  
  if (!apiKey) {
    throw new Error(
      'Anthropic API key not found. Please add VITE_ANTHROPIC_API_KEY to your .env.local file.'
    );
  }
  
  return new Anthropic({
    apiKey: apiKey,
    // Since we're calling from the browser, we need to use dangerouslyAllowBrowser
    // In production, you'd want to call this from a backend server instead
    dangerouslyAllowBrowser: true
  });
};

/**
 * Generate website content based on user description
 * 
 * @param {string} websiteDescription - User's description of their website needs
 * @param {string} contentType - Type of content to generate (default: 'complete')
 * @returns {Promise<Object>} Generated content object with headline, subheadline, and body
 */
export async function generateWebsiteContent(websiteDescription, contentType = 'complete') {
  
  // Validate input
  if (!websiteDescription || websiteDescription.trim().length === 0) {
    throw new Error('Please provide a description of your website.');
  }

  if (websiteDescription.trim().length < 10) {
    throw new Error('Please provide a more detailed description (at least 10 characters).');
  }

  try {
    const anthropic = getAnthropicClient();

    // System prompt that instructs Claude how to generate content
    const systemPrompt = `You are an expert website copywriter and content strategist. 
Your job is to create compelling, professional website content based on the user's description.

For each request, generate:
1. A catchy, attention-grabbing headline (max 60 characters)
2. A compelling subheadline that expands on the headline (max 120 characters)
3. 2-3 paragraphs of engaging body text (200-300 words total)

Guidelines:
- Use clear, concise language
- Focus on benefits, not just features
- Include a call-to-action when appropriate
- Match the tone to the business type (professional for B2B, friendly for consumer)
- Make content scannable with short paragraphs
- Use active voice and strong verbs
- Optimize for web reading (shorter sentences)

Return the content as a JSON object with this exact structure:
{
  "headline": "Your headline here",
  "subheadline": "Your subheadline here",
  "bodyText": "Paragraph 1\\n\\nParagraph 2\\n\\nParagraph 3"
}`;

    // Create the message to Claude
    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514', // Latest Claude Sonnet model
      max_tokens: 1024,
      temperature: 0.7, // Slightly creative but still focused
      system: systemPrompt,
      messages: [
        {
          role: 'user',
          content: `Generate website content for: ${websiteDescription}`
        }
      ]
    });

    // Extract the text response
    const responseText = message.content[0].text;

    // Parse the JSON response
    let generatedContent;
    try {
      // Claude might wrap JSON in markdown code blocks, so we need to extract it
      const jsonMatch = responseText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        generatedContent = JSON.parse(jsonMatch[0]);
      } else {
        generatedContent = JSON.parse(responseText);
      }
    } catch (parseError) {
      // If JSON parsing fails, create structured content from the response
      console.warn('Could not parse JSON, creating structured content from response');
      generatedContent = {
        headline: 'Generated Content',
        subheadline: 'Content generated by AI',
        bodyText: responseText
      };
    }

    // Validate the response has required fields
    if (!generatedContent.headline || !generatedContent.bodyText) {
      throw new Error('Generated content is missing required fields');
    }

    return {
      success: true,
      content: generatedContent,
      tokensUsed: message.usage.input_tokens + message.usage.output_tokens
    };

  } catch (error) {
    // Handle different types of errors
    if (error.message.includes('API key')) {
      throw new Error('API key error. Please check your Anthropic API key.');
    }
    
    if (error.status === 401) {
      throw new Error('Invalid API key. Please check your credentials.');
    }
    
    if (error.status === 429) {
      throw new Error('Rate limit exceeded. Please wait a moment and try again.');
    }
    
    if (error.status === 529) {
      throw new Error('Anthropic API is temporarily overloaded. Please try again in a moment.');
    }
    
    // Generic error
    console.error('AI Generation Error:', error);
    throw new Error(`Failed to generate content: ${error.message}`);
  }
}

// Export default for easier imports
export default {
  generateWebsiteContent
};